### ISSUE TITLE
Can I set TTL

### ISSUE THREAD

**Issue by marcoas** [pushpad/pushpad-php#3]
(Translated by Google)

Hello

Is it possible to configure a TTL ( time to live) ?
I mean, how long the notification is waiting to be delivered.
If the time expires, the notification becomes obsolete , and is eliminated

Thank you

**Comment by collimarco** [comment]
Hello! Currently Pushpad doesn't allow you to configure the TTL. Even if we had support for it, there are services like Apple Push Notification system that wouldn't support it anyway. Maybe we'll add it in the future when all services support it. Currently the TTL for Firefox (which supports the TTL) is set to 1 week.

**Comment by marcoas** [comment]
What a pity
Thank You

**Comment by collimarco** [comment]
TTL support is now available (except for Safari which doesn't support it): https://github.com/pushpad/pushpad-php/commit/c5659a0dbca0b128aeba2ddc8c3bd5291f2a01b7

**Comment by marcoas** [comment]
Gooooood news for me.
Thanks
