### ISSUE TITLE
Problem with deliver_to without tags

### ISSUE THREAD

**Issue by igorlovric** [pushpad/pushpad-php#4]
There is a problem with deliver_to function. I try to use example code, but I got error if I use this function like this: 

`$notification->deliver_to($user_ids);`

I fixed it by calling this function this way:

`$notification->deliver_to($user_ids, ["tags" => null]);`

In deliver_to function, just before this line (48):

`return $this->deliver($this->req_body($uids, $options['tags']), $options);`

there should be something like this:

`if (!isset($options['tags'])) {
     $options['tags']=null;
}`

**Comment by collimarco** [comment]
Hello! I don't see any _error_ there. Are you referring to the _notice_ for the undefined index?  It's just a coding style, I don't think it's an actual problem.

**Comment by igorlovric** [comment]
Hi,

Thank's for reply. Yes, I'm referring to notice, sorry for mistake. Usually, in development environment I have fallowing set:

`ini_set('display_errors', 1);`

So, when I make AJAX call to PHP function that send's notifications, and I expect some JSON as response, I get this JSON, but I also get notice about undefined index.

You are right, it's not actually big problem, but it would be easier for developer to work if they don't get notices when they call functions proper way.

**Comment by keisetsu** [comment]
This causes an exception to be called by Symfony, which means I can't call this without tags. It really would be preferable if a notice wasn't raised for something as common as this.
